//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessPointSimulator.AccessCheckService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccessCheckService.IAccessCheckService")]
    public interface IAccessCheckService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessCheckService/TryPass", ReplyAction="http://tempuri.org/IAccessCheckService/TryPassResponse")]
        bool TryPass(Vendor.API.AccessCheckDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessCheckService/TryPass", ReplyAction="http://tempuri.org/IAccessCheckService/TryPassResponse")]
        System.Threading.Tasks.Task<bool> TryPassAsync(Vendor.API.AccessCheckDto dto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccessCheckServiceChannel : AccessPointSimulator.AccessCheckService.IAccessCheckService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccessCheckServiceClient : System.ServiceModel.ClientBase<AccessPointSimulator.AccessCheckService.IAccessCheckService>, AccessPointSimulator.AccessCheckService.IAccessCheckService {
        
        public AccessCheckServiceClient() {
        }
        
        public AccessCheckServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccessCheckServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessCheckServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessCheckServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool TryPass(Vendor.API.AccessCheckDto dto) {
            return base.Channel.TryPass(dto);
        }
        
        public System.Threading.Tasks.Task<bool> TryPassAsync(Vendor.API.AccessCheckDto dto) {
            return base.Channel.TryPassAsync(dto);
        }
    }
}
