//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessSimulator.AccessPointRegistryProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccessPoint", Namespace="http://schemas.datacontract.org/2004/07/Vendor.API")]
    [System.SerializableAttribute()]
    public partial class AccessPoint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid AccessPointIdField;
        
        private string DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private string NameField;
        
        private string SiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid AccessPointId {
            get {
                return this.AccessPointIdField;
            }
            set {
                if ((this.AccessPointIdField.Equals(value) != true)) {
                    this.AccessPointIdField = value;
                    this.RaisePropertyChanged("AccessPointId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Site {
            get {
                return this.SiteField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteField, value) != true)) {
                    this.SiteField = value;
                    this.RaisePropertyChanged("Site");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccessPointRegistryProxy.IAccessPointRegistry")]
    public interface IAccessPointRegistry {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessPointRegistry/RegisterAccessPoint", ReplyAction="http://tempuri.org/IAccessPointRegistry/RegisterAccessPointResponse")]
        void RegisterAccessPoint(AccessSimulator.AccessPointRegistryProxy.AccessPoint dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessPointRegistry/RegisterAccessPoint", ReplyAction="http://tempuri.org/IAccessPointRegistry/RegisterAccessPointResponse")]
        System.Threading.Tasks.Task RegisterAccessPointAsync(AccessSimulator.AccessPointRegistryProxy.AccessPoint dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessPointRegistry/UnregisterAccessPoint", ReplyAction="http://tempuri.org/IAccessPointRegistry/UnregisterAccessPointResponse")]
        void UnregisterAccessPoint(System.Guid accessPointId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessPointRegistry/UnregisterAccessPoint", ReplyAction="http://tempuri.org/IAccessPointRegistry/UnregisterAccessPointResponse")]
        System.Threading.Tasks.Task UnregisterAccessPointAsync(System.Guid accessPointId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccessPointRegistryChannel : AccessSimulator.AccessPointRegistryProxy.IAccessPointRegistry, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccessPointRegistryClient : System.ServiceModel.ClientBase<AccessSimulator.AccessPointRegistryProxy.IAccessPointRegistry>, AccessSimulator.AccessPointRegistryProxy.IAccessPointRegistry {
        
        public AccessPointRegistryClient() {
        }
        
        public AccessPointRegistryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccessPointRegistryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessPointRegistryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessPointRegistryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RegisterAccessPoint(AccessSimulator.AccessPointRegistryProxy.AccessPoint dto) {
            base.Channel.RegisterAccessPoint(dto);
        }
        
        public System.Threading.Tasks.Task RegisterAccessPointAsync(AccessSimulator.AccessPointRegistryProxy.AccessPoint dto) {
            return base.Channel.RegisterAccessPointAsync(dto);
        }
        
        public void UnregisterAccessPoint(System.Guid accessPointId) {
            base.Channel.UnregisterAccessPoint(accessPointId);
        }
        
        public System.Threading.Tasks.Task UnregisterAccessPointAsync(System.Guid accessPointId) {
            return base.Channel.UnregisterAccessPointAsync(accessPointId);
        }
    }
}
