//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessPointSimulator.AccessPointRegistry {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccessPointRegistry.IAccessPointRegistry")]
    public interface IAccessPointRegistry {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessPointRegistry/RegisterAccessPoint", ReplyAction="http://tempuri.org/IAccessPointRegistry/RegisterAccessPointResponse")]
        void RegisterAccessPoint(Vendor.API.AccessPointDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessPointRegistry/RegisterAccessPoint", ReplyAction="http://tempuri.org/IAccessPointRegistry/RegisterAccessPointResponse")]
        System.Threading.Tasks.Task RegisterAccessPointAsync(Vendor.API.AccessPointDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessPointRegistry/UnregisterAccessPoint", ReplyAction="http://tempuri.org/IAccessPointRegistry/UnregisterAccessPointResponse")]
        void UnregisterAccessPoint(System.Guid accessPointId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessPointRegistry/UnregisterAccessPoint", ReplyAction="http://tempuri.org/IAccessPointRegistry/UnregisterAccessPointResponse")]
        System.Threading.Tasks.Task UnregisterAccessPointAsync(System.Guid accessPointId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccessPointRegistryChannel : AccessPointSimulator.AccessPointRegistry.IAccessPointRegistry, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccessPointRegistryClient : System.ServiceModel.ClientBase<AccessPointSimulator.AccessPointRegistry.IAccessPointRegistry>, AccessPointSimulator.AccessPointRegistry.IAccessPointRegistry {
        
        public AccessPointRegistryClient() {
        }
        
        public AccessPointRegistryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccessPointRegistryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessPointRegistryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessPointRegistryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RegisterAccessPoint(Vendor.API.AccessPointDto dto) {
            base.Channel.RegisterAccessPoint(dto);
        }
        
        public System.Threading.Tasks.Task RegisterAccessPointAsync(Vendor.API.AccessPointDto dto) {
            return base.Channel.RegisterAccessPointAsync(dto);
        }
        
        public void UnregisterAccessPoint(System.Guid accessPointId) {
            base.Channel.UnregisterAccessPoint(accessPointId);
        }
        
        public System.Threading.Tasks.Task UnregisterAccessPointAsync(System.Guid accessPointId) {
            return base.Channel.UnregisterAccessPointAsync(accessPointId);
        }
    }
}
