//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessSimulator.AccessCheckServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckAccess", Namespace="http://schemas.datacontract.org/2004/07/Vendor.API")]
    [System.SerializableAttribute()]
    public partial class CheckAccess : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid AccessPointIdField;
        
        private string UserHashField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid AccessPointId {
            get {
                return this.AccessPointIdField;
            }
            set {
                if ((this.AccessPointIdField.Equals(value) != true)) {
                    this.AccessPointIdField = value;
                    this.RaisePropertyChanged("AccessPointId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UserHash {
            get {
                return this.UserHashField;
            }
            set {
                if ((object.ReferenceEquals(this.UserHashField, value) != true)) {
                    this.UserHashField = value;
                    this.RaisePropertyChanged("UserHash");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccessCheckServiceProxy.IAccessCheckService")]
    public interface IAccessCheckService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessCheckService/TryPass", ReplyAction="http://tempuri.org/IAccessCheckService/TryPassResponse")]
        bool TryPass(AccessSimulator.AccessCheckServiceProxy.CheckAccess dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessCheckService/TryPass", ReplyAction="http://tempuri.org/IAccessCheckService/TryPassResponse")]
        System.Threading.Tasks.Task<bool> TryPassAsync(AccessSimulator.AccessCheckServiceProxy.CheckAccess dto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccessCheckServiceChannel : AccessSimulator.AccessCheckServiceProxy.IAccessCheckService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccessCheckServiceClient : System.ServiceModel.ClientBase<AccessSimulator.AccessCheckServiceProxy.IAccessCheckService>, AccessSimulator.AccessCheckServiceProxy.IAccessCheckService {
        
        public AccessCheckServiceClient() {
        }
        
        public AccessCheckServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccessCheckServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessCheckServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessCheckServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool TryPass(AccessSimulator.AccessCheckServiceProxy.CheckAccess dto) {
            return base.Channel.TryPass(dto);
        }
        
        public System.Threading.Tasks.Task<bool> TryPassAsync(AccessSimulator.AccessCheckServiceProxy.CheckAccess dto) {
            return base.Channel.TryPassAsync(dto);
        }
    }
}
